### PR TITLE
Add login, logout, indexing structure

### PR DESCRIPTION
**Pull request by lijinyang0228**
This change is [Reviewable](https://reviewable.io/reviews/minhyukpark/dataspreadfrontend/4)

### CODE REVIEW

**Comment by lijinyang0228** [comment]
+@minhyukpark

**Comment by lijinyang0228** [comment]
___
*[src/components/sqlgrid/index.js, line 388 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadfrontend/4#-Lwf-xFdE5gFzZLEQ_QM:-LwfCfx3C6zhhEOAbusK:b-7ql1td) ([raw file](https://github.com/minhyukpark/dataspreadfrontend/blob/03680718bfd39683a03a3a35d55687548eb9ed57/src/components/sqlgrid/index.js#L388)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

This comparison should be `rowArr !== undefined`
</blockquote></details>

fixed

**Comment by lijinyang0228** [comment]
___
*[src/components/sqlgrid/index.js, line 810 at r3](https://reviewable.io/reviews/minhyukpark/dataspreadfrontend/4#-Lx-ALjd8Uuos3JeqO7v:-LxAGdcQ9WcZXxAKcO8G:b-oja1iq) ([raw file](https://github.com/minhyukpark/dataspreadfrontend/blob/0c7bb7b130fcba620c1b206e2c582b1cf306031d/src/components/sqlgrid/index.js#L810)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

This endpoint should be changed right?
</blockquote></details>

already changed to /updaterow

**Comment by MinhyukPark** [comment]
Have you done tests other than running a few scenarios? I don't think tests are necessary but I just wanted to check.

**Comment by lijinyang0228** [comment]
No. Will do it soon.

**Comment by MinhyukPark** [comment]
@kevinccchang

**Pull request merged**
